#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# This template is responsible for bulding a docker image and saving it as an artifact.

steps:
  - task: Docker@2
    displayName: 'Docker Build'
    inputs:
      repository: ${{ parameters.serviceName }}
      command: build
      Dockerfile: '$(DOCKERFILE)'
      tags: $(Build.BuildId)
      buildContext: "."
      arguments: "--build-arg VSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN)"

  - task: Docker@2
    displayName: 'Docker Save'
    inputs:
      repository: ${{ parameters.serviceName }}
      command: save
      arguments: '--output $(build.artifactstagingdirectory)/${{ parameters.serviceName }}.image.tar ${{ parameters.serviceName }}:$(Build.BuildId)'
      addPipelineData: false
