# Default values for indexer-queue-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requestsCpu: "0.1"
  requestsMemory: "384M"
  limitsCpu: "1"
  limitsMemory: "1G"
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "indexer-queue"
conf:
  appName: "indexer-queue"
  configmap: "indexer-queue-config"
  keycloakSecretName: "indexer-queue-keycloak-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  onPremEnabled: false
  domain: ""
