variables:
  OSDU_GCP_SERVICE: indexer-queue
  OSDU_GCP_VENDOR: gcp-cloudrun
  BUILD_PATH: "$OSDU_GCP_SERVICE-$OSDU_GCP_VENDOR/cloudbuild/Dockerfile.cloudbuild"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.log_level=DEBUG
    --set data.osdu_entitlements_url=$OSDU_GCP_AUTHORIZE_API
    --set data.google_cloud_project=$OSDU_GCP_PROJECT
    --set data.google_cloud_project_region=$OSDU_GCP_CLOUDRUN_REGION
    --set data.cloud_task_target_host=$OSDU_GCP_CLOUD_TASK_TARGET_HOST
    --set data.partition_api=$OSDU_GCP_PARTITION_API
    --set data.google_audiences=$GOOGLE_AUDIENCE
    --set data.indexer_queue_identifier=$OSDU_GCP_INDEXER_QUEUE_CLOUDTASK_NAME

osdu-gcp-test:
  extends:
    - .maven
    - .osdu-gcp-variables
  stage: integration
  needs: ["osdu-gcp-deploy-deployment"]
  allow_failure: true
  script:
    - echo "This is a stub. Integration tests are not implemented for the Indexer-Queue service."
    - exit 1

osdu-gcp-dev2-test:
  extends:
    - .maven
    - .osdu-gcp-dev2-variables
  stage: integration
  needs: ["osdu-gcp-dev2-deploy-deployment"]
  allow_failure: true
  script:
    - echo "This is a stub. Integration tests are not implemented for the Indexer-Queue service."
    - exit 1
