variables:
  AWS_BUILD_SUBDIR: indexer-queue-aws
  AWS_APPLICATION_NAME: os-indexer-queue
  AWS_ENVIRONMENT: dev

include:
  - project: 'osdu/platform/ci-cd-pipelines'
    ref: 'master'
    file: 'temp-service.gitlab-ci.yml'
