variables:
  AWS_BUILD_SUBDIR: indexer-queue-aws/build-aws
  AWS_TEST_SUBDIR: indexer-queue-aws
  AWS_SERVICE: indexer-queue
  AWS_ENVIRONMENT: dev

  IBM_BUILD_SUBDIR: indexer-queue-ibm

  AZURE_SERVICE: enque
  AZURE_BUILD_SUBDIR: indexer-queue-azure-enqueue
  AZURE_TEST_SUBDIR: indexer-queue-azure-enqueue

  GCP_BUILD_SUBDIR: indexer-queue-gcp
  GCP_INT_TEST_SUBDIR: indexer-queue-gcp # Fix as soon as integration tests are added
  GCP_APPLICATION_NAME: osdu-indexer-queue
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com

  OSDU_GCP_BUILD_SUBDIR: indexer-queue-gcp
  OSDU_GCP_INT_TEST_SUBDIR: indexer-queue-gcp # Fix as soon as integration tests are added
  OSDU_GCP_ENVIRONMENT: osdu-gcp
  OSDU_GCP_TENANT_NAME: osdu
  OSDU_GCP_SERVICE: indexer-queue
  OSDU_GCP_APPLICATION_NAME: indexer-queue
  OSDU_GCP_VENDOR: gcp-cloudrun
  OSDU_GCP_INDEXER_HOST_4Q: https://os-indexer-attcrcktoa-uc.a.run.app
  OSDU_GCP_IQ_SA: pub-sub-indexer-queue@nice-etching-277309.iam.gserviceaccount.com
  OSDU_GCP_ENV_VARS: GOOGLE_AUDIENCES=$GOOGLE_AUDIENCE,GOOGLE_CLOUD_PROJECT_REGION=$OSDU_GCP_CLOUDRUN_REGION,GOOGLE_CLOUD_PROJECT=$OSDU_GCP_PROJECT,INDEXER_HOST=$OSDU_GCP_INDEXER_HOST_4Q,SERVICE_MAIL=$OSDU_GCP_IQ_SA,OSDU_ENTITLEMENTS_URL=$OSDU_GCP_ENTITLEMENTS_URL --vpc-connector=$OSDU_GCP_VPC_CONNECTOR

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws.yml"

  - project: 'osdu/platform/ci-cd-pipelines'
    file: 'cloud-providers/ibm-deploy-only.yml'

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure-function.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gcp.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-cloudrun.yml"

gcp-deploy:
  image: divido2/gcp-maven
  stage: deploy
  extends:
    - .gcp
    - .maven

  script:
    - mkdir -p gcp_deploy_dir
    - gcloud auth activate-service-account --key-file="$GCP_DEPLOY_FILE"
    - sed -e "s|ENVIRONMENT|$GCP_ENVIRONMENT|g" "$GCP_BUILD_SUBDIR/src/main/webapp/WEB-INF/appengine-web.xml"
    - cat $GCP_BUILD_SUBDIR/src/main/webapp/WEB-INF/appengine-web.xml
    - $MAVEN package appengine:deploy -pl org.opengroup.osdu.indexerqueue:indexer-queue-gcp -Dapp.deploy.project=$GCP_PROJECT -Dapp.deploy.version=$CI_COMMIT_SHORT_SHA -DskipTests=true

gcp-test:
  extends:
    - .gcp
    - .maven
    - .gcp_variables
  stage: integration
  needs: ["gcp-deploy"]
  script:
    - echo "This is a stub. Integration tests are not implemented for the Indexer-Queue service."

osdu-gcp-containerize:
  stage: containerize
  needs: ["compile-and-unit-test"]
  extends: .osdu-gcp-variables
  image: google/cloud-sdk
  cache: {}
  script:
    - gcloud auth activate-service-account --key-file $OSDU_GCP_DEPLOY_FILE
    - gcloud config set project $OSDU_GCP_PROJECT
    - touch .gcloudignore
    - gcloud builds submit --config $OSDU_GCP_SERVICE-$OSDU_GCP_VENDOR/cloudbuild/cloudbuild.yaml --substitutions=_GCP_SERVICE=$OSDU_GCP_SERVICE,_APPLICATION_NAME=$OSDU_GCP_APPLICATION_NAME,_PROVIDER_NAME=$OSDU_GCP_VENDOR,_SHORT_SHA=$CI_COMMIT_SHORT_SHA,_PORT=$OSDU_GCP_PORT
  only:
    variables:
      - $OSDU_GCP == 'true'

osdu-gcp-test:
  extends:
    - .maven
    - .osdu-gcp-variables
  stage: integration
  needs: ["osdu-gcp-deploy"]
  allow_failure: true
  script:
    - echo "This is a stub. Integration tests are not implemented for the Indexer-Queue service."
    - exit 1
