{{- template "common.serviceaccount" (list . "os-indexer-queue.serviceaccount") -}}
{{- define "os-indexer-queue.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}