# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - .gitignore

pool:
  name: dps-build
  demands: maven

steps:
  - task: Maven@3
    displayName: "build, test, code coverage"
    inputs:
      mavenPomFile: "indexer-queue-gc/pom.xml"
      options: "--settings indexer-queue-ibm/configuration/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN)"
      testResultsFiles: "**/*/TEST-*.xml"
      codeCoverageToolOption: JaCoCo
      goals: "clean install -U"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
    condition: succeededOrFailed()
