variables:
  GC_SERVICE: indexer-queue
  GC_VENDOR: gc-cloudrun
  BUILD_PATH: "$GC_SERVICE-$GC_VENDOR/cloudbuild/Dockerfile.cloudbuild"
  GC_HELM_SETS: >-
    --set data.cloudTaskTargetHost=$OSDU_GCP_CLOUD_TASK_TARGET_HOST 
    --set data.indexerQueueIdentifier=$OSDU_GCP_INDEXER_QUEUE_CLOUDTASK_NAME

gc-test:
  extends:
    - .maven
    - .gc-variables
  stage: integration
  needs: ["gc-deploy-deployment"]
  allow_failure: true
  script:
    - echo "This is a stub. Integration tests are not implemented for the Indexer-Queue service."
    - exit 1

gc-dev2-test:
  extends:
    - .maven
    - .gc-dev2-variables
  stage: integration
  needs: ["gc-dev2-deploy-deployment"]
  allow_failure: true
  script:
    - echo "This is a stub. Integration tests are not implemented for the Indexer-Queue service."
    - exit 1

gc-anthos-test:
  allow_failure: true
  script:
    - echo "This is a stub. The service doesn't support the step."
    - exit 1
